# Generated by Django 6.0.1 on 2026-01-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('policy_text', models.TextField()),
                ('sentiment_score', models.FloatField()),
                ('risk_score', models.IntegerField()),
                ('detected_categories', models.JSONField()),
                ('detected_keywords', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
