# Generated by Django 6.0.1 on 2026-03-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacyanalysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Privacy Analysis', 'verbose_name_plural': 'Privacy Analyses'},
        ),
        migrations.RemoveField(
            model_name='privacyanalysis',
            name='detected_keywords',
        ),
        migrations.RemoveField(
            model_name='privacyanalysis',
            name='risk_score',
        ),
        migrations.AddField(
            model_name='privacyanalysis',
            name='consent_risk_score',
            field=models.IntegerField(default=0, help_text='Calculated risk score (0 to 100)'),
        ),
        migrations.AddField(
            model_name='privacyanalysis',
            name='is_manual_paste',
            field=models.BooleanField(default=False, help_text='True if the user pasted the text manually'),
        ),
        migrations.AddField(
            model_name='privacyanalysis',
            name='safety_score',
            field=models.FloatField(default=0.0, help_text='Calculated safety rating (1.0 to 5.0 stars)'),
        ),
        migrations.AlterField(
            model_name='privacyanalysis',
            name='detected_categories',
            field=models.JSONField(default=dict, help_text='Dictionary of detected risk categories'),
        ),
        migrations.AlterField(
            model_name='privacyanalysis',
            name='policy_text',
            field=models.TextField(help_text='The full text of the privacy policy analyzed'),
        ),
        migrations.AlterField(
            model_name='privacyanalysis',
            name='sentiment_score',
            field=models.FloatField(default=0.0, help_text='NLP sentiment polarity (-1.0 to 1.0)'),
        ),
        migrations.AlterField(
            model_name='privacyanalysis',
            name='source',
            field=models.CharField(help_text="Name of the App or 'Pasted Policy'", max_length=255),
        ),
    ]
